/**
 * Engagement Prompt Pool — 50 prompts across 7 categories.
 *
 * Content sourced from TENDER_ENGAGEMENT_50_PROMPTS.md.
 * Evidence-backed, warm, witty, never shaming.
 * Tone: Wes Anderson meets attachment theory.
 */

import { Colors } from '@/constants/theme';
import {
  BookOpenIcon,
  LightbulbIcon,
  MasksIcon,
  TargetIcon,
  SeedlingIcon,
  HeartDoubleIcon,
  FireIcon,
  BrainIcon,
  HeartPulseIcon,
  HandshakeIcon,
  SparkleIcon,
  EyeIcon,
  CompassIcon,
  WaveIcon,
} from '@/assets/graphics/icons';
import type {
  EngagementPrompt,
  CategoryConfig,
  NotificationCategory,
  EngagementNotificationPreferences,
} from '@/types/notifications';

// ─── Category Configuration ────────────────────────────

export const CATEGORY_CONFIG: CategoryConfig[] = [
  {
    id: 'science_drop',
    label: 'Science Drops',
    description: 'Research-backed relationship facts',
    icon: BookOpenIcon,
    accentColor: Colors.secondary,
    maxPerWeek: 3,
  },
  {
    id: 'micro_insight',
    label: 'Micro-Insights',
    description: 'Perspective shifts from relationship science',
    icon: LightbulbIcon,
    accentColor: Colors.calm,
    maxPerWeek: 3,
  },
  {
    id: 'duolingo_wit',
    label: 'Playful Prompts',
    description: 'Lighthearted relationship humor',
    icon: MasksIcon,
    accentColor: Colors.accentGold,
    maxPerWeek: 2,
  },
  {
    id: 'practice_nudge',
    label: 'Practice Reminders',
    description: 'Gentle reminders to try an exercise',
    icon: TargetIcon,
    accentColor: Colors.primary,
    maxPerWeek: 5,
  },
  {
    id: 'growth_mirror',
    label: 'Growth Mirrors',
    description: 'Reflections on your progress',
    icon: SeedlingIcon,
    accentColor: Colors.success,
    maxPerWeek: 2,
  },
  {
    id: 'couple_bubble',
    label: 'Couple Warmth',
    description: 'Messages celebrating your connection',
    icon: HeartDoubleIcon,
    accentColor: Colors.primaryLight,
    maxPerWeek: 2,
  },
  {
    id: 'milestone_streak',
    label: 'Milestones',
    description: 'Celebrations for streaks and achievements',
    icon: FireIcon,
    accentColor: Colors.accentCream,
    maxPerWeek: 7, // trigger-based, no hard cap
  },
];

// ─── Default Preferences ────────────────────────────────

export const DEFAULT_ENGAGEMENT_PREFS: EngagementNotificationPreferences = {
  scienceDrops: true,
  microInsights: true,
  duolingoWit: true,
  practiceNudges: true,
  growthMirrors: true,
  coupleBubble: true,
  milestoneStreak: true,
};

// ─── Preference → Category Mapping ──────────────────────

export const PREF_TO_CATEGORY: Record<keyof EngagementNotificationPreferences, NotificationCategory> = {
  scienceDrops: 'science_drop',
  microInsights: 'micro_insight',
  duolingoWit: 'duolingo_wit',
  practiceNudges: 'practice_nudge',
  growthMirrors: 'growth_mirror',
  coupleBubble: 'couple_bubble',
  milestoneStreak: 'milestone_streak',
};

// ─── The 50 Prompts ─────────────────────────────────────

export const ENGAGEMENT_PROMPTS: EngagementPrompt[] = [
  // ═══════════════════════════════════════════════════════
  // SCIENCE DROPS (1–12)
  // ═══════════════════════════════════════════════════════

  {
    id: 'science-01',
    category: 'science_drop',
    title: 'The magic ratio is 5:1.',
    body: 'Happy couples have 5 positive interactions for every negative one. Not 50:1. Not perfection. Just five small moments of warmth for every hard one.',
    source: 'Gottman, 40+ years of research',
    tags: ['gottman', 'positivity', 'ratio'],
    priority: 8,
    icon: BookOpenIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-02',
    category: 'science_drop',
    title: 'Six seconds can change your whole day.',
    body: 'A 6-second kiss when you say goodbye. Long enough to actually feel something. Most couples average a peck shorter than a swipe. Try it tomorrow morning.',
    source: 'Gottman Institute',
    tags: ['gottman', 'ritual', 'connection'],
    priority: 7,
    icon: BookOpenIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-03',
    category: 'science_drop',
    title: '69% of relationship problems are unsolvable.',
    body: "That's not depressing \u2014 it's liberating. Most conflicts are perpetual. The goal isn't to fix them. It's to learn to dance with them.",
    source: 'Gottman longitudinal studies',
    tags: ['gottman', 'conflict', 'perpetual'],
    priority: 9,
    icon: BookOpenIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-04',
    category: 'science_drop',
    title: 'Your nervous system has a favorite person.',
    body: "Brain scans show that holding your partner's hand reduces the neural threat response more than holding a stranger's hand. Your body already knows.",
    source: 'James Coan, UVA fMRI research',
    tags: ['neuroscience', 'co-regulation', 'touch'],
    weareTarget: 'attunement',
    priority: 8,
    icon: BrainIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-05',
    category: 'science_drop',
    title: 'Researchers can predict divorce with 94% accuracy.',
    body: "Not from how much you fight. From HOW you fight. Contempt is the #1 predictor. The antidote? Building a culture of appreciation. That's what we're practicing here.",
    source: 'Gottman "Love Lab" studies',
    tags: ['gottman', 'contempt', 'appreciation'],
    priority: 9,
    icon: BookOpenIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-06',
    category: 'science_drop',
    title: "Your attachment style isn't your destiny.",
    body: "Research shows attachment patterns can shift \u2014 especially with a partner who responds consistently. Every time you show up here, you're literally rewiring your nervous system.",
    source: 'Fraley et al., longitudinal attachment research',
    tags: ['attachment', 'neuroplasticity', 'change'],
    weareTarget: 'resistance',
    priority: 8,
    icon: BrainIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-07',
    category: 'science_drop',
    title: 'You have a force field. Use it.',
    body: 'Stan Tatkin calls it the "couple bubble" \u2014 a mutual agreement to protect the relationship above outside pressures. Couples with a strong bubble recover from conflict 40% faster.',
    source: 'Tatkin, PACT research',
    tags: ['tatkin', 'couple-bubble', 'protection'],
    weareTarget: 'space',
    priority: 7,
    icon: HeartDoubleIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-08',
    category: 'science_drop',
    title: 'The best love stories start boring.',
    body: "66% of romantic relationships begin as friendships. The slow burn is real. Gottman's research says friendship IS the foundation \u2014 not passion, not chemistry.",
    source: 'Stinson et al., 2022; Gottman Method',
    tags: ['friendship', 'foundation'],
    priority: 6,
    icon: BookOpenIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-09',
    category: 'science_drop',
    title: "The #1 skill in happy relationships isn't communication.",
    body: "It's repair. Not never hurting each other \u2014 that's impossible. But catching it, naming it, reaching back. Couples who make repair attempts stay together.",
    source: 'Gottman, The Marriage Clinic',
    tags: ['repair', 'skill', 'gottman'],
    weareTarget: 'transmission',
    priority: 9,
    icon: BookOpenIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-10',
    category: 'science_drop',
    title: '70% of distressed couples recover.',
    body: "Emotionally Focused Therapy \u2014 the modality that informs much of what you're learning here \u2014 has a 70% recovery rate. Gains last 2+ years. Doing the work actually works.",
    source: 'Sue Johnson, EFT outcome studies',
    tags: ['eft', 'recovery', 'hope'],
    priority: 8,
    icon: BookOpenIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-11',
    category: 'science_drop',
    title: 'Your partner made a bid today. Did you catch it?',
    body: '"Bids for connection" are small moments: a sigh, a question, a look. Happy couples turn TOWARD bids 86% of the time. Unhappy couples? Only 33%.',
    source: 'Gottman, "turning toward" research',
    tags: ['bids', 'turning-toward', 'connection'],
    weareTarget: 'attunement',
    priority: 8,
    icon: EyeIcon,
    accentColor: Colors.secondary,
  },
  {
    id: 'science-12',
    category: 'science_drop',
    title: "Gratitude isn't just nice. It's neurochemistry.",
    body: 'Expressing appreciation to your partner releases oxytocin in both of you. Not just the receiver \u2014 the giver too.',
    source: 'Algoe et al., PNAS research on gratitude in relationships',
    tags: ['gratitude', 'oxytocin', 'appreciation'],
    weareTarget: 'transmission',
    priority: 7,
    icon: SparkleIcon,
    accentColor: Colors.secondary,
  },

  // ═══════════════════════════════════════════════════════
  // MICRO-INSIGHTS (13–22)
  // ═══════════════════════════════════════════════════════

  {
    id: 'insight-13',
    category: 'micro_insight',
    title: 'That thing they do that drives you crazy?',
    body: 'It protected them once. Every frustrating pattern your partner has was once a survival strategy. Understanding where it came from changes everything.',
    tags: ['patterns', 'empathy', 'history'],
    weareTarget: 'resistance',
    priority: 8,
    icon: LightbulbIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-14',
    category: 'micro_insight',
    title: 'The relationship is the third thing.',
    body: "It's not just you. It's not just them. There's a living thing between you \u2014 and it needs tending. When was the last time you asked the relationship what IT needs?",
    tags: ['third-entity', 'relational-field'],
    weareTarget: 'coCreation',
    priority: 7,
    icon: LightbulbIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-15',
    category: 'micro_insight',
    title: 'Anger is a bodyguard.',
    body: 'Underneath almost every angry reaction is something softer \u2014 fear, hurt, loneliness. Next conflict, try asking: what\'s underneath this?',
    tags: ['anger', 'primary-emotions', 'eft'],
    priority: 8,
    icon: LightbulbIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-16',
    category: 'micro_insight',
    title: "You're not broken. You're dancing.",
    body: "One pursues, one withdraws. It's the most common relational pattern on earth. Neither role is wrong \u2014 both are trying to manage the same fear: disconnection.",
    tags: ['pursue-withdraw', 'dance', 'eft'],
    priority: 9,
    icon: LightbulbIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-17',
    category: 'micro_insight',
    title: "Security isn't boring. It's brave.",
    body: "People think secure attachment means no spark. Actually, it means you can be vulnerable without armor. That takes more courage than any wall ever did.",
    tags: ['secure', 'vulnerability', 'attachment'],
    priority: 7,
    icon: LightbulbIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-18',
    category: 'micro_insight',
    title: "You can't think clearly when your nervous system is screaming.",
    body: "When you're flooded \u2014 heart racing, jaw tight \u2014 your brain literally can't process complex emotions. Step 1 isn't \"talk it out.\" Step 1 is: come back to your body.",
    tags: ['flooding', 'window-of-tolerance', 'polyvagal'],
    weareTarget: 'context',
    priority: 8,
    icon: BrainIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-19',
    category: 'micro_insight',
    title: 'The paradox of closeness.',
    body: "The closer you want to be, the more you need a solid sense of yourself. Bowen called this differentiation \u2014 the ability to stay connected without losing yourself.",
    tags: ['differentiation', 'bowen', 'self'],
    weareTarget: 'space',
    priority: 7,
    icon: CompassIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-20',
    category: 'micro_insight',
    title: 'What kind of partner do you want to be today?',
    body: "Not \"what do you want your partner to do.\" What do YOU want to embody? Living by your values \u2014 even imperfectly \u2014 is the best predictor of relationship satisfaction.",
    tags: ['values', 'act', 'agency'],
    weareTarget: 'coCreation',
    priority: 7,
    icon: CompassIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-21',
    category: 'micro_insight',
    title: 'Happy couples fight too.',
    body: "The difference? They repair. All couples fight. Healthy couples have fights where both people feel heard, even when they disagree. That's a skill \u2014 and you're building it.",
    tags: ['conflict', 'repair', 'normalization'],
    priority: 7,
    icon: LightbulbIcon,
    accentColor: Colors.calm,
  },
  {
    id: 'insight-22',
    category: 'micro_insight',
    title: 'Criticism. Contempt. Defensiveness. Stonewalling.',
    body: "These aren't personality traits. They're habits. And habits can change. You wouldn't still be here if you didn't believe that.",
    tags: ['four-horsemen', 'gottman', 'change'],
    weareTarget: 'change',
    priority: 8,
    icon: LightbulbIcon,
    accentColor: Colors.calm,
  },

  // ═══════════════════════════════════════════════════════
  // DUOLINGO-STYLE WIT (23–32)
  // ═══════════════════════════════════════════════════════

  {
    id: 'wit-23',
    category: 'duolingo_wit',
    title: 'Quick relationship check',
    body: "You remembered to charge your phone today. Can you also remember to ask your partner how their day was? Both take about 30 seconds. One has better long-term returns.",
    tags: ['humor', 'bids'],
    priority: 7,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-24',
    category: 'duolingo_wit',
    title: 'Your relationship > your queue.',
    body: "You spent 45 minutes choosing a movie last night. Spend 3 minutes on a Tender practice today. We promise it's more rewarding than rewatching The Office.",
    tags: ['humor', 'practice'],
    priority: 6,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-25',
    category: 'duolingo_wit',
    title: "A therapist's worst nightmare:",
    body: "\"We don't really fight.\" (They do. They just stopped trying.) You're here because you haven't stopped trying. That's actually everything.",
    tags: ['humor', 'normalization'],
    priority: 7,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-26',
    category: 'duolingo_wit',
    title: 'Seen at 2:47 PM.',
    body: "Your partner's love language probably isn't \"left on read.\" A 2-minute Tender practice takes less time than composing the perfect \"sorry I was busy\" text.",
    tags: ['humor', 'communication'],
    priority: 6,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-27',
    category: 'duolingo_wit',
    title: 'If attachment styles had dating profiles:',
    body: "Anxious: \"I texted you 3 minutes ago?\" Avoidant: \"I need space (but don't actually leave).\" Secure: \"I'll be here.\" Which profile are you editing today?",
    tags: ['humor', 'attachment'],
    priority: 8,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-28',
    category: 'duolingo_wit',
    title: "You've been thinking about that thing they said.",
    body: "The one from Tuesday. We know. Before you draft your 4th mental paragraph of rebuttal \u2014 try a 2-minute grounding practice. Your nervous system will write a better response.",
    tags: ['humor', 'rumination', 'grounding'],
    priority: 7,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-29',
    category: 'duolingo_wit',
    title: 'Rating your last apology:',
    body: "\"Sorry you feel that way\" \u2014 2/10. \"Sorry, but...\" \u2014 3/10. \"I'm sorry I hurt you. Tell me more.\" \u2014 10/10. There's a practice for that.",
    tags: ['humor', 'repair', 'apology'],
    priority: 7,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-30',
    category: 'duolingo_wit',
    title: '"We need to talk."',
    body: "Four words that activate every nervous system on earth. What if instead you tried: \"I noticed something and I want to understand it with you.\" Same conversation. 60% less cortisol.",
    tags: ['humor', 'gentle-startup'],
    priority: 8,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-31',
    category: 'duolingo_wit',
    title: 'Rest days are part of the program.',
    body: "Even Olympic athletes take rest days. If you skipped yesterday, good. Your relationship didn't fall apart. It's right here waiting. No guilt. No streak drama. Just a door that's always open.",
    tags: ['humor', 'anti-shame', 'rest'],
    weareTarget: 'context',
    priority: 7,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },
  {
    id: 'wit-32',
    category: 'duolingo_wit',
    title: 'Somewhere right now, two people are having the same fight for the 47th time.',
    body: 'And somewhere else, two people just figured out the fight was never about the dishes. It was about feeling seen. 3-minute practice. That\'s all.',
    tags: ['humor', 'perpetual-problems'],
    priority: 7,
    icon: MasksIcon,
    accentColor: Colors.accentGold,
  },

  // ═══════════════════════════════════════════════════════
  // PRACTICE NUDGES (33–40)
  // ═══════════════════════════════════════════════════════

  {
    id: 'practice-33',
    category: 'practice_nudge',
    title: '2 minutes. No phones. Just eyes.',
    body: 'Sit across from each other. Set a timer. Just breathe and look. 2 minutes of mutual gaze increases oxytocin and decreases cortisol. It will feel awkward. Do it anyway.',
    tags: ['practice', 'presence', 'gaze'],
    weareTarget: 'attunement',
    priority: 8,
    icon: TargetIcon,
    accentColor: Colors.primary,
  },
  {
    id: 'practice-34',
    category: 'practice_nudge',
    title: "Pop quiz: What's stressing your partner most right now?",
    body: "Gottman calls this a \"love map\" \u2014 your internal model of your partner's world. It needs updating. Like software. Ask them tonight. Listen for 60 seconds without fixing.",
    tags: ['practice', 'love-map', 'listening'],
    weareTarget: 'attunement',
    priority: 8,
    icon: TargetIcon,
    accentColor: Colors.primary,
  },
  {
    id: 'practice-35',
    category: 'practice_nudge',
    title: "How's the space between you today?",
    body: "Not good or bad. Just notice. Is it tight? Open? Warm? Distant? Naming the temperature is the first step to tending it.",
    tags: ['practice', 'check-in', 'awareness'],
    priority: 7,
    icon: TargetIcon,
    accentColor: Colors.primary,
  },
  {
    id: 'practice-36',
    category: 'practice_nudge',
    title: 'One thing. Just one.',
    body: "Think of one specific thing your partner did this week that you appreciated. Not \"you're great.\" Something specific. Specificity is the language of attention.",
    tags: ['practice', 'appreciation', 'specificity'],
    weareTarget: 'transmission',
    priority: 8,
    icon: TargetIcon,
    accentColor: Colors.primary,
  },
  {
    id: 'practice-37',
    category: 'practice_nudge',
    title: 'Before the hard conversation...',
    body: 'Check your body first. Shoulders? Jaw? Breath? If your nervous system is already at an 8, your conversation will start at an 8. Come down to a 5 first.',
    tags: ['practice', 'regulation', 'body'],
    weareTarget: 'context',
    priority: 7,
    icon: TargetIcon,
    accentColor: Colors.primary,
  },
  {
    id: 'practice-38',
    category: 'practice_nudge',
    title: 'Make one bid today.',
    body: "Say their name. Ask a question. Share something small. Every bid is a tiny question: \"Are you there? Do I matter?\" Happy couples make dozens a day. Start with one.",
    tags: ['practice', 'bids', 'connection'],
    weareTarget: 'attunement',
    priority: 8,
    icon: TargetIcon,
    accentColor: Colors.primary,
  },
  {
    id: 'practice-39',
    category: 'practice_nudge',
    title: 'Something felt off yesterday?',
    body: "You don't have to wait for the \"right moment\" to repair. Successful repair attempts are often clumsy, imperfect, and badly timed \u2014 but they work because they're real.",
    tags: ['practice', 'repair', 'courage'],
    weareTarget: 'transmission',
    priority: 7,
    icon: TargetIcon,
    accentColor: Colors.primary,
  },
  {
    id: 'practice-40',
    category: 'practice_nudge',
    title: "Relationship work doesn't require two people today.",
    body: "Understanding your own patterns is half the equation. Today's practice is just for you \u2014 your nervous system, your patterns, your growing edges.",
    tags: ['practice', 'solo', 'self-awareness'],
    weareTarget: 'individual',
    priority: 6,
    icon: TargetIcon,
    accentColor: Colors.primary,
  },

  // ═══════════════════════════════════════════════════════
  // GROWTH MIRRORS (41–44)
  // ═══════════════════════════════════════════════════════

  {
    id: 'growth-41',
    category: 'growth_mirror',
    title: 'You keep showing up.',
    body: "That rhythm changes everything. Not perfection. Not daily streaks. Just the pattern of returning. Research says it's the RETURN that builds the habit, not the streak.",
    tags: ['growth', 'rhythm', 'habit'],
    priority: 8,
    icon: SeedlingIcon,
    accentColor: Colors.success,
  },
  {
    id: 'growth-42',
    category: 'growth_mirror',
    title: 'Remember when this felt unfamiliar?',
    body: "The practices that feel natural now once felt strange. That shift IS the change. You're not the same person who downloaded this app.",
    tags: ['growth', 'progress', 'change'],
    minDay: 14,
    priority: 7,
    icon: SeedlingIcon,
    accentColor: Colors.success,
  },
  {
    id: 'growth-43',
    category: 'growth_mirror',
    title: 'Couples who do the work stay together.',
    body: "Not because they're perfect. Because they built something \u2014 a shared language, a repair reflex, a way of seeing each other that holds even when things get hard.",
    tags: ['growth', 'commitment', 'resilience'],
    minDay: 21,
    priority: 7,
    icon: SeedlingIcon,
    accentColor: Colors.success,
  },
  {
    id: 'growth-44',
    category: 'growth_mirror',
    title: 'If the same issue came up again \u2014 good.',
    body: "Growth isn't linear. It's a spiral. You'll meet the same themes again, but you're different each time. Notice what's different this time.",
    tags: ['growth', 'spiral', 'patterns'],
    weareTarget: 'change',
    minDay: 7,
    priority: 7,
    icon: SeedlingIcon,
    accentColor: Colors.success,
  },

  // ═══════════════════════════════════════════════════════
  // COUPLE BUBBLE (45–48)
  // ═══════════════════════════════════════════════════════

  {
    id: 'bubble-45',
    category: 'couple_bubble',
    title: "How's your couple bubble?",
    body: "Couples who protect the space between them \u2014 who put the relationship first, even during stress \u2014 recover faster and fight less. Your bubble is an agreement. Renew it today.",
    tags: ['bubble', 'tatkin', 'protection'],
    weareTarget: 'space',
    priority: 7,
    icon: HeartDoubleIcon,
    accentColor: Colors.primaryLight,
  },
  {
    id: 'bubble-46',
    category: 'couple_bubble',
    title: 'Feed the thing between you.',
    body: "Your relationship is not just two people. It's a third, living thing that needs attention, humor, honesty, and rest. What has it eaten this week?",
    tags: ['bubble', 'third-entity', 'tending'],
    weareTarget: 'coCreation',
    priority: 7,
    icon: HeartDoubleIcon,
    accentColor: Colors.primaryLight,
  },
  {
    id: 'bubble-47',
    category: 'couple_bubble',
    title: 'Your nervous system is contagious.',
    body: "When you're calm, your partner's nervous system can borrow your calm. Tonight, try being the calm one first. Not performing calm \u2014 actually breathing into it.",
    tags: ['bubble', 'co-regulation', 'polyvagal'],
    weareTarget: 'attunement',
    priority: 8,
    icon: HeartPulseIcon,
    accentColor: Colors.primaryLight,
  },
  {
    id: 'bubble-48',
    category: 'couple_bubble',
    title: "Home isn't a place. It's a nervous system.",
    body: "Attachment theory says we all need a \"secure base\" \u2014 someone we can launch from and return to. The strongest relationships are the ones where coming back always feels safe.",
    tags: ['bubble', 'secure-base', 'safety'],
    weareTarget: 'space',
    priority: 8,
    icon: WaveIcon,
    accentColor: Colors.primaryLight,
  },

  // ═══════════════════════════════════════════════════════
  // MILESTONE & STREAK (49–50)
  // ═══════════════════════════════════════════════════════

  {
    id: 'milestone-49',
    category: 'milestone_streak',
    title: '7 days in.',
    body: "You've been here a week. Most people who try relationship work quit after 3 days. You didn't. That's not a small thing. The research says this is exactly where habits start to stick.",
    tags: ['milestone', 'first-week', 'habit'],
    minDay: 7,
    maxFrequency: 'once',
    priority: 10,
    icon: FireIcon,
    accentColor: Colors.accentCream,
  },
  {
    id: 'milestone-50',
    category: 'milestone_streak',
    title: 'Hey. Welcome back.',
    body: "No guilt. No \"where have you been.\" Life happens. The door is always open and your progress is right where you left it. The fact that you came back says more than a streak ever could.",
    tags: ['milestone', 'return', 'anti-shame'],
    maxFrequency: 'biweekly',
    priority: 10,
    icon: SparkleIcon,
    accentColor: Colors.accentCream,
  },
];

// ─── Helpers ────────────────────────────────────────────

/** Get category config by ID. */
export function getCategoryConfig(id: NotificationCategory): CategoryConfig | undefined {
  return CATEGORY_CONFIG.find((c) => c.id === id);
}

/** Get all prompts for a given category. */
export function getPromptsByCategory(category: NotificationCategory): EngagementPrompt[] {
  return ENGAGEMENT_PROMPTS.filter((p) => p.category === category);
}
